### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by FDominicus** [AccessCodeLib/AccUnit#27]
The installation has worked up to the point in the Video where one type
TestSuite.name in the window
I loaded the database TestRunner.accdb
While trying to tun the test I just get:
Der Typ 'AccessCoddLib.common.VBIDETools.CodeModuleMember in der Assembly "AccessCodLib.VBIDETools,Version=0.9.10.0, Culture=Neutral, PublicKeyToken=null konnte nicht geladen werden 

And that's it ...

**Comment by FDominicus** [comment]
SimpleTest seems to run, TestClassWithSetup runs, RowTestClass does nothing?

Am using: Microsoft Access 2021 MSO (Version 2307 Build. 16.0.16626.20170) 32 bit

**Comment by FDominicus** [comment]
And there is a problem with vbunit, which probably defines Errror$ and  so one has to remove the reference to it
or you get compilation errors on every Error$, and that's breaks everything ...

Sorry ...

**Comment by FDominicus** [comment]
Affirmative VBunit has Error$ defined and tha obviously clashes with MS Access version of it. I am surprised that it seems to work for others ...

**Comment by FDominicus** [comment]
And me again I loaded the TestRunner.accdb and added a Module 
This is the code:
`Option Compare Database
Option Explicit

Public Sub testIt()
    

On Error GoTo HandleError
    

HandleExit:
    Exit Sub


HandleError:
    MsgBox Error$
    If Err.Number <> 0 Then
       MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure testIt."
    End If
    GoTo HandleExit


End Sub`

Trying to compile: 
Fehler beim Compilieren Error$ mehrdeutig.
Benutzt man nicht Error$ kommt man wohl irgendwie drum herum

**Comment by josef-poetzl** [comment]
What do you mean by VBunit?
AccUnit does not define Error$ anywhere.

**Comment by FDominicus** [comment]
The installation says:

Installation SimplyVbUnit 3.0
Für die Verwendung von AccUnit muss SimplyVBUnit 3.0 installiert sein. SimplyVBUnit ist ein in Visual Basic 6 geschriebenes Testframework. Weitere Informationen zu SimplyVBUnit finden Sie auf der Projektseite von SimplyVBUnit auf sourceforge.

Laden Sie die Setup-Datei von SimplyVBUnit 3.0 hier herunter.

I guess it is for things like Iz and the like

But if I do so, i run into a problem with error handling  in Acccess where there's just something like
MsgBox Error$

If the reference to SimpleVBUnit is set this won't compile any more. 



-- 
Q-Software Solutions GmbH
Kraichgaustr. 11, 76646 Bruchsal
Tel: 07251/35 98 92, Fax: 07251/35 98 91
HRB 232138 Reg Mannheim

**Comment by josef-poetzl** [comment]
Ok, jetzt verstehe ich das Problem. Das war für die "alte" Version von AccUnit.
(Leider hänge ich mit der WebSite-Anpassung noch etwas hinterher.)

Die Version hier auf GitHub kommt ohne SimplyVbUnit aus. Ich entfernte SimplyVbUnit, weil damit AccUnit nicht mit 64-Bit-Access verwendet werden konnte. Außerdem stellte ich von einem COM-Add-In auf ein einfaches Access-Add-In um, damit muss nichts in Windows installiert werden.

Zum Laufen lassen der aktuellen Version ist nur das Installieren des AccUnitLoader-Add-Ins erforderlich.

Zum Testen fügte ich noch ein Beispiel mit dem Aufruf der Tests über TestSuite an.
https://github.com/AccessCodeLib/AccUnit/blob/main/examples/msaccess/TestSuiteExamples.accdb

**Comment by FDominicus** [comment]
Ich verstehe, dann werde ich noch mal von vorne anfangen

**Comment by FDominicus** [comment]
Danke, ich habe von vorne angefangen und es mal ausprobiert und es läuft. Ich freue mich, danke schön.

**Comment by josef-poetzl** [comment]
Danke für die Info. Freut mich, dass es nun funktioniert.
Hier gibt es eine kurze Übersicht wie man die Tests starten kann: [How‐to: Run tests with AccUnit‐Loader (Access add‐in)](https://github.com/AccessCodeLib/AccUnit/wiki/How%E2%80%90to:-Run-tests-with-AccUnit%E2%80%90Loader-(Access-add%E2%80%90in))
