### ISSUE TITLE
I cannot load AccUnit from the add-ins list

### ISSUE THREAD

**Issue by PioPio2** [AccessCodeLib/AccUnit#71]
Hello,

I have installed the add-in successfully but when I try to load it from the IDE I receive the error message 'AccUnit VBE Add-in' could not be loaded. Remove it from the list of available add-ins?

I can see the add-in in Access Add-in manager, I can also activate the Add-in form, I can export the DLL files from add-in, I can set the reference and also Insert/update AccUnit Factory module in my test application.
I can see the files AccUnit.dll, AccUnit.tlb and AccUnit.VbeAddIn.dll in C:\USERS\ADMIN\APPDATA\ROAMING\MICROSOFT\ADDINS\lib\ and I have added the folder above in the list of the trusted locations.

I have Win 7 32 bit on my machine, Access 2016 and AccuUnit 0.9.10000.240519

Is there anything else I should do in order to load the add-in?

Many thanks
Alberto

**Comment by josef-poetzl** [comment]
Hi!

Win 7 ... is the .NET Framework 4.8 installed?
This is required for the VBE add-in.

Note:
The call via the immediate window without installed VBE-Add-In works with .net-Framework 3.5.

Josef

**Comment by PioPio2** [comment]
Hi Josef,

I have installed both .NET Framework 4.7.1 and 4.8

What else can I do ?

Many thanks
Alberto

**Comment by josef-poetzl** [comment]
> I can see the files AccUnit.dll, AccUnit.tlb and AccUnit.VbeAddIn.dll 

There should be 5 files.
- AccUnit.dll
- AccUnit.tlb
- AccUnit.VbeAddIn.dll
- AccessCodeLib.Common.Tools.dll
- AccessCodeLib.Common.VbeUserControlHost.dll
- AccessCodeLib.Common.VBIDETools.dll

Can you please check this.

**Comment by PioPio2** [comment]
Hi Josef,

Yes, they are all there now.

**Comment by PioPio2** [comment]
Hi again, 

If this can help find the error.

- I tried to uninstall and re-install the Add-in but the issue still exists. If I try to load AccUnit VBE Add-in from the "Access Code Library" form I get the error message "Error -2147024894 (Method 'Connect' of Object 'Addin' failed) in procedure cmLoadVBEAddin_click. All the other options work as they should.
- I don't have the additional menu item under "Tool" in the IDE related to AccUnit 
- If I type "? TestSuite.Name" in the immediate window I get "AccUnitLoader TestSuite".

**Comment by josef-poetzl** [comment]
I am attaching the debug.dll variant.
[debug-lib.zip](https://github.com/user-attachments/files/17534068/debug-lib.zip)

This allows you to view the debug output with [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), for example.
However, I fear that the error occurs even before Connect is called via the IDTExtensibility2 interface.
Unfortunately, I no longer have Win7 available for testing.

**Comment by PioPio2** [comment]
I have Windows 11 Pro now and I am trying to install the add-in
