### ISSUE TITLE
Intellisense not working on Assert only

### ISSUE THREAD

**Issue by PioPio2** [AccessCodeLib/AccUnit#76]
Hello,

On my first Test, I noticed the IntelliSense is not working however, the feature works for other classes as normal, see the video in the attachment. The app compiles with no errors. 
I have Win 11 Pro 64 bit, Office 2021

https://github.com/user-attachments/assets/eac0d967-39d2-4bc2-bccb-953569dff8ff

What am I missing?

Many thanks
Alberto

**Comment by josef-poetzl** [comment]
This depends on whether you use Late or Early binding for AccUnit.

Early binding:
1. Open Add-In (Access-Add-In) 
2. Set reference to AccUnit.tlb
3. Install/update AccUnit Factory modul

**Comment by PioPio2** [comment]
Thanks, it works now
