### ISSUE TITLE
Test Explorer

### ISSUE THREAD

**Issue by PioPio2** [AccessCodeLib/AccUnit#77]
Hello,

A nice-to-have feature would be to double-click on a specific test in the Test explorer and the cursor would jump at the beginning of the Sub ready to be edited.

Many thanks
Alberto

**Comment by josef-poetzl** [comment]
This is already built in. However, it is not called up via a double-click, but via a button. :)
![AccUnit-Source](https://github.com/user-attachments/assets/2f2a2669-68f2-472f-862e-14d56cd8998b)
![AccUnit-Source_testresult](https://github.com/user-attachments/assets/966ff28b-5a33-4e9e-ae56-5f60d36b5aa9)

**Comment by PioPio2** [comment]
Hello,

How strange, I cannot see any button on mine
![Screenshot 2024-11-26 210544](https://github.com/user-attachments/assets/534ff2bd-1372-4c87-bc7e-d9a58a5f530c)

My Framework version is 0.9.10.0 and the Add-In version is 0.9.2.0 Is there a more updated one ? I have installed the add-in a few days ago.

**Comment by PioPio2** [comment]
Hello,

How strange, I cannot see any button on mine
![Screenshot 2024-11-26 210544](https://github.com/user-attachments/assets/534ff2bd-1372-4c87-bc7e-d9a58a5f530c)

My Framework version is 0.9.10.0 and the Add-In version is 0.9.2.0 Is there a more updated one ? I have installed the add-in a few days ago.

I have just double checked the references and they look ok
![2 Screenshot 2024-11-26 210924](https://github.com/user-attachments/assets/15f7a29a-d85e-4da7-963f-2518424f56c4)

**Comment by josef-poetzl** [comment]
Add-In should be 0.9.3. Found the bug: The Access add-in still contains 0.9.2.

**Comment by PioPio2** [comment]
Hi Josef,

Updated installed and working! Thank you
Alberto
